services:
  postgres:
    container_name: opennote-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: manh
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: opennote_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - opennote-net

  redis:
    container_name: opennote-redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - opennote-net

volumes:
  postgres_data:
  redis_data:

networks:
  opennote-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
